import Head from "next/head";
import style from '../styles/layout.module.css'
import Menu from "./Menu";

export default function Layout({children, title}){
  return(
    <>
    <Head>
      <title>{title ? title : 'Tienda'}</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Menu></Menu>
    <div className={style.container}>
      {children}
    </div>
    </>
  )
}